modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-Quark/issues"

[[mods]]
modId="dtquark"
version="${file.jarVersion}"
displayName="Dynamic Trees for Quark"
logoFile="dtquark_logo.png"
authors="Max Hyper, Violet Moon"
description='''
Compatibility Mod between Dynamic Trees and Quark for NeoForge 1.21.1
'''

[[dependencies.dtquark]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtquark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtquark]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtquark]]
    modId="quark"
    mandatory=true
    versionRange="[4.1,)"
    ordering="AFTER"
    side="BOTH"
